/**
 * Turns Natural Earth's coastlines and country borders into line segments for
 * the globe.
 *
 * `mesh` gives every boundary exactly once: run over the country topology with
 * a filter that keeps only shared edges and you get internal borders; run it
 * over the land topology and you get coastlines. Both come out as real
 * geometry, so the globe shows the actual world rather than an impression of
 * it.
 *
 * Data: world-atlas 1:50m (Natural Earth, public domain).
 * Regenerate with `npm run globe:map`.
 */
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { mesh } from "topojson-client";

const require = createRequire(import.meta.url);
const countries = require("world-atlas/countries-50m.json");
const land = require("world-atlas/land-50m.json");

/** Degrees → a point on the unit sphere, the same mapping the globe uses. */
function toXYZ(lon, lat) {
  const phi = ((90 - lat) * Math.PI) / 180;
  const theta = ((lon + 180) * Math.PI) / 180;
  return [
    -Math.sin(phi) * Math.cos(theta),
    Math.cos(phi),
    Math.sin(phi) * Math.sin(theta),
  ];
}

/**
 * Flattens a MultiLineString into gl.LINES pairs, dropping points that sit
 * closer together than `minStep` degrees — Natural Earth is denser than a
 * globe this size can show, and the dropped points are invisible at any zoom
 * the page allows.
 */
function segments(geometry, minStep) {
  const out = [];
  for (const line of geometry.coordinates) {
    let previous = null;
    for (const [lon, lat] of line) {
      if (previous) {
        const step = Math.hypot(lon - previous[0], lat - previous[1]);
        if (step < minStep) continue;
        // A span that crosses the antimeridian would cut through the globe.
        if (Math.abs(lon - previous[0]) > 180) {
          previous = [lon, lat];
          continue;
        }
        out.push(...toXYZ(previous[0], previous[1]), ...toXYZ(lon, lat));
      }
      previous = [lon, lat];
    }
  }
  return out;
}

// 0.6° ≈ 66 km, and the globe renders at about 25 km per pixel, so nothing
// dropped here could have been seen.
const coast = segments(mesh(land, land.objects.land), 0.6);
const borders = segments(mesh(countries, countries.objects.countries, (a, b) => a !== b), 0.6);

// Three decimals on a unit sphere is about 6 km: four times finer than a pixel.
const round = (n) => Math.round(n * 1000) / 1000;
const body = `/**
 * The world, as line geometry on the unit sphere.
 *
 * Generated by \`scripts/globe/borders.mjs\` from Natural Earth 1:50m via the
 * world-atlas package (public domain). COAST holds every coastline and
 * BORDERS every land boundary between two countries, both as gl.LINES pairs
 * of xyz triples. Regenerate with \`npm run globe:map\`.
 */

export const COAST = new Float32Array([${coast.map(round).join(",")}]);

export const BORDERS = new Float32Array([${borders.map(round).join(",")}]);
`;

writeFileSync(new URL("../../src/design/depth/gl/world.ts", import.meta.url), body);
console.log("coast points:", coast.length / 3, "| border points:", borders.length / 3, "| KB:", Math.round(body.length / 1024));
