/**
 * Turns real cities into the globe's night side.
 *
 * A night-time satellite view is not scattered dots: it is where people
 * actually live, which is why the eastern United States glows and the Sahara
 * does not. This takes GeoNames' populated places, keeps the ones above a
 * population floor, and writes each as a point on the sphere with a
 * brightness taken from how many people live there.
 *
 * Data: GeoNames via the `all-the-cities` package, CC BY 4.0.
 * Regenerate with `npm run globe:lights`.
 */
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const cities = require("all-the-cities");

const FLOOR = 90_000;
const kept = cities.filter((city) => city.population >= FLOOR);

const positions = [];
const sizes = [];

for (const city of kept) {
  const [lon, lat] = city.loc.coordinates;
  const phi = ((90 - lat) * Math.PI) / 180;
  const theta = ((lon + 180) * Math.PI) / 180;
  positions.push(
    -Math.sin(phi) * Math.cos(theta),
    Math.cos(phi),
    Math.sin(phi) * Math.sin(theta),
  );
  // Log scale: a city of ten million is not a hundred times the dot of a city
  // of a hundred thousand, it is roughly twice it — which is how the real
  // photographs read.
  sizes.push(Math.round((0.45 + Math.log10(city.population / FLOOR) * 0.75) * 100) / 100);
}

const round = (n) => Math.round(n * 1000) / 1000;
const body = `/**
 * The world's cities, as points on the unit sphere with a brightness each.
 *
 * Generated by \`scripts/globe/lights.mjs\` from GeoNames populated places
 * (CC BY 4.0, via the all-the-cities package): every city above ${FLOOR.toLocaleString("en-GB")}
 * people, ${kept.length.toLocaleString("en-GB")} of them. Regenerate with \`npm run globe:lights\`.
 */

export const LIGHTS = new Float32Array([${positions.map(round).join(",")}]);

export const LIGHT_SIZES = new Float32Array([${sizes.join(",")}]);
`;

writeFileSync(new URL("../../src/design/depth/gl/lights.ts", import.meta.url), body);
console.log("cities:", kept.length, "| KB:", Math.round(body.length / 1024));
